import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
  weight: [ '200', '400', '700' ],
  subsets: [ 'latin' ]
})

export const metadata = {
  title: 'Omni Coffee & Eggs',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.svg'
  }
}

export default function RootLayout ({ children })
{
  return (
    <html lang="en">
      <body className={ poppins.className }>{ children }</body>
    </html>
  )
}
