import styles from './page.module.css'

// export const metadata = {
//   title: 'Omni Coffee & Eggs',
//   description: 'Generated by create next app',
//   icons: {
//     icon: '/icon.svg'
//   }
// }

const HomePage = () =>
{
  return (
    <div className={ styles.HomePage }>
      <h1>HomePage</h1>
    </div>
  )
}

export default HomePage